/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-08-02 02:14:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>忘记密码－修改成功</title>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\"/>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"resources/css/jquery-ui-themes.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"resources/css/axure_rp_page.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"data/styles.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"files/忘记密码－修改成功/styles.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <script src=\"resources/scripts/jquery-1.7.1.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/scripts/jquery-ui-1.8.10.custom.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/scripts/prototypePre.js\"></script>\r\n");
      out.write("    <script src=\"data/document.js\"></script>\r\n");
      out.write("    <script src=\"resources/scripts/prototypePost.js\"></script>\r\n");
      out.write("    <script src=\"files/忘记密码－修改成功/data.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      $axure.utils.getTransparentGifPath = function() { return 'resources/images/transparent.gif'; };\r\n");
      out.write("      $axure.utils.getOtherPath = function() { return 'resources/Other.html'; };\r\n");
      out.write("      $axure.utils.getReloadPath = function() { return 'resources/reload.html'; };\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction validate()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar uname = document.getElementById(\"uname\");\r\n");
      out.write("\t\t\tvar upwd = document.getElementById(\"upwd\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (uname.value==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"请填写登录名！\");\r\n");
      out.write("\t\t\t\tuname.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif (upwd.value==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"请填写密码！\");\r\n");
      out.write("\t\t\t\tupwd.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction mysubmit(){\r\n");
      out.write("\t\t\tvar uname = $(\"#uname\").val();\r\n");
      out.write("\t\t\tvar upwd = $(\"#upwd\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(validate()){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t//用来跳转的url\r\n");
      out.write("\t\t\t\t\turl:\"login.do?uname=\"+uname+\"&upwd=\"+upwd,\r\n");
      out.write("\t\t\t\t\t//数据提交方式\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\t//返回到页面的数据类型\r\n");
      out.write("\t\t\t\t\tdatatype:\"String\",\r\n");
      out.write("\t\t\t\t\t//成功后调用的方法\r\n");
      out.write("\t\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(result == \"ok\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"登录成功\");\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href=\"homePageLogged.jsp\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"用户名或密码错误\");\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href=\"userLogin.jsp\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"base\" class=\"\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Unnamed (矩形) -->\r\n");
      out.write("      <div id=\"u98\" class=\"ax_default box_2\">\r\n");
      out.write("        <div id=\"u98_div\" class=\"\"></div>\r\n");
      out.write("        <!-- Unnamed () -->\r\n");
      out.write("        <div id=\"u99\" class=\"text\" style=\"display:none; visibility: hidden\">\r\n");
      out.write("          <p><span></span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Unnamed (矩形) -->\r\n");
      out.write("      <div id=\"u100\" class=\"ax_default shape\">\r\n");
      out.write("        <div id=\"u100_div\" class=\"\"></div>\r\n");
      out.write("        <!-- Unnamed () -->\r\n");
      out.write("        <div id=\"u101\" class=\"text\" style=\"display:none; visibility: hidden\">\r\n");
      out.write("          <p><span></span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Unnamed (矩形) -->\r\n");
      out.write("      <div id=\"u102\" class=\"ax_default _形状1\">\r\n");
      out.write("        <div id=\"u102_div\" class=\"\"></div>\r\n");
      out.write("        <!-- Unnamed () -->\r\n");
      out.write("        <div id=\"u103\" class=\"text\" style=\"display:none; visibility: hidden\">\r\n");
      out.write("          <p><span></span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Unnamed (矩形) -->\r\n");
      out.write("      <div id=\"u106\" class=\"ax_default shape\">\r\n");
      out.write("        <div id=\"u106_div\" class=\"\">\r\n");
      out.write("        \t<center>\r\n");
      out.write("      \t\t\t<div style=\"width: 500px;\">\r\n");
      out.write("      \t\t\t\t<form action=\"login.do\" method=\"post\" class=\"form-horizontal\" >\r\n");
      out.write("      \t\t\t\t\t<h4 style=\"margin-top: 100px; font-weight: 800;\"\">用户登录</h4><br /><br /><br />\r\n");
      out.write("\t\t\t  \t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t    \t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#zhlogin\" aria-controls=\"zhlogin\" role=\"tab\" data-toggle=\"tab\">账号登录</a></li>\r\n");
      out.write("\t\t\t    \t\t\t<li role=\"presentation\"><a href=\"#yzmlogin\" aria-controls=\"yzmlogin\" role=\"tab\" data-toggle=\"tab\">验证码登录</a></li>\r\n");
      out.write("\t\t\t  \t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t    \t\t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"zhlogin\"><br />\r\n");
      out.write("\t\t\t    \t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-8\">\r\n");
      out.write("\t\t\t      \t\t\t\t\t\t<input name=\"uname\" type=\"text\" class=\"form-control\" id=\"uname\" placeholder=\"请输入用户名\" required=\"required\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t    \t\t\t<div class=\"col-sm-offset-2 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t<input name=\"upwd\" type=\"password\" class=\"form-control\" id=\"upwd\" placeholder=\"请输入密码\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t    \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 用户名的登录 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t    \t\t\t<div class=\"col-sm-offset-2 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t<button type=\"button\" onclick=\"mysubmit()\" class=\"btn btn-primary btn-lg\" style=\"height: auto;width: 323.33px;\">登录</button><br /><br />\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t<a href=\"userRegister.jsp\">\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-lg\" style=\"height: auto;width: 323.33px;\">注册</button>\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t    \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t        <p class=\"text-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t        \t<a href=\"forgetPwd1.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t        \t\t<button type=\"button\" class=\"btn btn-link\">忘记密码</button>\r\n");
      out.write("\t\t\t\t\t\t\t        \t</a>\r\n");
      out.write("\t\t\t\t\t\t\t        </p>\r\n");
      out.write("\t\t\t\t\t\t\t    </div>\t\t\r\n");
      out.write("\t\t\t\t    \t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"yzmlogin\"><br />\r\n");
      out.write("\t\t\t\t    \t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-8\">\r\n");
      out.write("\t\t\t      \t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"uname\" name=\"uname\" placeholder=\"请输入手机号/账号\">\r\n");
      out.write("\t\t\t    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"upwd\" name=\"upwd\" placeholder=\"请输入验证码\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t<div class=\" col-sm-2\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-default\">获取验证码</button>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 用验证码的登录 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t    \t\t\t<div class=\"col-sm-offset-2 col-sm-8\">\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t<button type=\"button\" onclick=\"mysubmit()\" class=\"btn btn-primary btn-lg\" style=\"height: auto;width: 323.33px;\">登录</button><br /><br />\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t<a href=\"userRegister.jsp\">\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-lg\" style=\"height: auto;width: 323.33px;\">注册</button>\r\n");
      out.write("\t\t\t\t\t      \t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t    \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t\r\n");
      out.write("\t\t\t\t    \t</div>\t\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Unnamed () -->\r\n");
      out.write("        <div id=\"u107\" class=\"text\" style=\"display:none; visibility: hidden\">\r\n");
      out.write("          <p><span></span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Unnamed (矩形) -->\r\n");
      out.write("      <div id=\"u132\" class=\"ax_default _二级标题\">\r\n");
      out.write("        <div id=\"u132_div\" class=\"\"></div>\r\n");
      out.write("        <!-- Unnamed () -->\r\n");
      out.write("        <div id=\"u133\" class=\"text\">\r\n");
      out.write("          <p><span>职业培训网络大学</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Unnamed (矩形) -->\r\n");
      out.write("      <div id=\"u134\" class=\"ax_default shape\">\r\n");
      out.write("        <div id=\"u134_div\" class=\"\"></div>\r\n");
      out.write("        <!-- Unnamed () -->\r\n");
      out.write("        <div id=\"u135\" class=\"text\">\r\n");
      out.write("          <p><span>LO</span></p><p><span>GO</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
